#!/usr/bin/env python3
"""
Turn a PNG into a sprite MARIA can actually read.

    python tools/mksprite.py ship.png --label ship -o ship.asm
    python tools/mksprite.py rocks.png --frames 12 --label rock -o rocks.asm
    python tools/mksprite.py ship.png --mode 320A --label text -o text.asm

`spriteedit.py` paints artwork that is already in a cartridge. This puts new
artwork in, which is a different problem and mostly one of layout: a
direct-mode object is not a bitmap. MARIA fetches one scanline per PAGE, and
the offset counts DOWN, so the rows come out bottom-first, 256 bytes apart,
and the display list points at the LAST row. Emit a flat run of bytes instead
-- the obvious thing, and what every image library hands you -- and the object
draws one row of your art repeated down its height.

Several frames of an animation pack side by side at a stride equal to one
frame's width, sharing the same pages. That is the layout the sprite sheets in
shipping cartridges use, and `--frames N` writes it.

Colours are indices into a MARIA palette, not RGB. In 160A each pixel is two
bits (four colours, index 0 being the background and therefore transparent);
in 320A each pixel is one bit. Give the image only that many distinct colours
and they map by luminance, darkest to index 0, or say so explicitly with
--colours.
"""
import argparse
import os
import sys

MODES = {
    "160A": (2, 4),      # bits per pixel, pixels per byte
    "320A": (1, 8),
}


def load(path):
    try:
        from PIL import Image
    except ImportError:
        raise SystemExit("mksprite needs Pillow: pip install pillow")
    return Image.open(path).convert("RGB")


def build_map(img, bpp, explicit):
    """Map RGB tuples to colour indices."""
    limit = 1 << bpp
    seen = sorted({img.getpixel((x, y))
                   for y in range(img.height) for x in range(img.width)},
                  key=lambda c: 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2])
    if explicit:
        m = {}
        for pair in explicit.split(","):
            col, idx = pair.split("=")
            col = col.strip().lstrip("#")
            m[(int(col[0:2], 16), int(col[2:4], 16), int(col[4:6], 16))] = int(idx)
        missing = [c for c in seen if c not in m]
        if missing:
            raise SystemExit("--colours does not cover %s"
                             % ", ".join("#%02x%02x%02x" % c for c in missing[:4]))
        return m
    if len(seen) > limit:
        raise SystemExit(
            "image has %d distinct colours; %s allows %d.\nReduce the palette, "
            "or map them yourself with --colours '#000000=0,#ffffff=1,...'"
            % (len(seen), "this mode", limit))
    return {c: i for i, c in enumerate(seen)}


def pack(img, mode, frames, cmap):
    """-> (rows, width_bytes): rows[y] is the packed bytes for scanline y."""
    bpp, ppb = MODES[mode]
    if img.width % (frames * ppb):
        raise SystemExit(
            "image is %d pixels wide; with %d frame(s) in %s that must be a "
            "multiple of %d" % (img.width, frames, mode, frames * ppb))
    fw = img.width // frames                      # pixels per frame
    width_bytes = fw // ppb
    rows = []
    for y in range(img.height):
        row = bytearray()
        for f in range(frames):
            for b in range(width_bytes):
                v = 0
                for p in range(ppb):
                    x = f * fw + b * ppb + p
                    idx = cmap[img.getpixel((x, y))]
                    v |= (idx & ((1 << bpp) - 1)) << (8 - bpp * (p + 1))
                row.append(v)
        rows.append(bytes(row))
    return rows, width_bytes


def emit(rows, width_bytes, frames, label, mode, src):
    per_page = len(rows[0])
    if per_page > 256:
        raise SystemExit("%d bytes per scanline exceeds one 256-byte page"
                         % per_page)
    L = []
    a = L.append
    a("; %s -- generated by mksprite.py from %s" % (label, os.path.basename(src)))
    a("; %d frame(s), %d bytes wide, %d scanlines, %s"
      % (frames, width_bytes, len(rows), mode))
    a(";")
    a("; Point a display list entry at `%s` and give it width %d."
      % (label, width_bytes))
    a("; Rows are stored BOTTOM-FIRST, one page apart, because MARIA's zone")
    a("; offset counts down: the top scanline is fetched from the highest")
    a("; page. The label is the bottom row, which is the address the display")
    a("; list wants.")
    if frames > 1:
        a("; Frame f starts at %s + f*%d, in the same pages."
          % (label, width_bytes))
    a("")
    for k, row in enumerate(reversed(rows)):
        scan = len(rows) - 1 - k
        if k == 0:
            a("%s:" % label)
        a("    .byte %s   ; scanline %d%s"
          % (",".join("$%02X" % b for b in row), scan,
             " (bottom, the DL points here)" if k == 0 else ""))
        if k != len(rows) - 1:
            a("    .res $100-%d,$00" % per_page)
    a("")
    return "\n".join(L) + "\n"


def unpack(rows, width_bytes, frames, mode):
    """Inverse of pack(), for the round-trip check in selftest."""
    bpp, ppb = MODES[mode]
    out = []
    for row in rows:
        px = []
        for b in row:
            for p in range(ppb):
                px.append((b >> (8 - bpp * (p + 1))) & ((1 << bpp) - 1))
        out.append(px)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__)
    ap.add_argument("image")
    ap.add_argument("-o", "--out", help="write assembly here (default: stdout)")
    ap.add_argument("--label", default="sprite")
    ap.add_argument("--mode", choices=sorted(MODES), default="160A")
    ap.add_argument("--frames", type=int, default=1,
                    help="frames packed side by side in the image")
    ap.add_argument("--colours", "--colors", dest="colours",
                    help="explicit map, e.g. '#000000=0,#ffffff=1'")
    ap.add_argument("--bin", help="also write the raw packed rows here")
    args = ap.parse_args()

    if args.frames < 1:
        raise SystemExit("--frames must be at least 1")
    img = load(args.image)
    bpp, _ = MODES[args.mode]
    cmap = build_map(img, bpp, args.colours)
    rows, width_bytes = pack(img, args.mode, args.frames, cmap)
    text = emit(rows, width_bytes, args.frames, args.label, args.mode, args.image)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote %s: %d frame(s), %d bytes wide, %d scanlines"
              % (args.out, args.frames, width_bytes, len(rows)))
    else:
        sys.stdout.write(text)
    if args.bin:
        with open(args.bin, "wb") as f:
            for row in reversed(rows):
                f.write(row)
        print("wrote %s" % args.bin)
    return 0


if __name__ == "__main__":
    sys.exit(main())
