#!/usr/bin/env python3
"""
Start a 7800 game: a project that assembles, boots, and puts a moving sprite
on screen.

    python tools/newgame.py mygame --title "My Game"
    python tools/newgame.py mygame --build          # also write mygame/game.a78

Every other tool here reads a cartridge somebody else wrote. This one writes
the smallest cartridge that is still a real one, because the gap between "I
have an assembler" and "MARIA is drawing what I meant" is where 7800 projects
die, and almost none of that gap is 6502 -- it is the two-level display list,
the offset that counts down, and a sprite layout that is nothing like a
bitmap.

What the generated source is for is being edited. It is commented at the
density of an explanation rather than a program, and every constant that came
out of a shipping cartridge says so, because the alternative is a scaffold
that works for reasons the reader cannot see.

The register values are not invented. CTRL $40 (DMA on, 160A) and $60 (DMA
off, for setup) are what shipping 1987 cartridges write to $3C; the INPTCTRL
sequence follows the same games. See docs/hardware.md for the bit layouts and
docs/pitfalls.md for what goes wrong.
"""
import argparse
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

ROM_BASE = 0xC000
ROM_SIZE = 0x4000
GFX_PAGE = 0xD0          # sprite rows live at $D000,$D100,... one page apart
SPRITE_LINES = 8
SPRITE_WIDTH = 4         # bytes; 160A mode packs 4 pixels per byte -> 16 wide
ZONE_LINES = 16
ZONES = 12               # 12 * 16 = 192 visible scanlines

# 160A mode: two bits per pixel, selecting colour 0-3 within one palette.
# Colour 0 is the background and reads as transparent, so it is the '.' here.
SHIP = [
    ".......11.......",
    "......1221......",
    "......1221......",
    ".....122221.....",
    "....12233221....",
    "...1223333221...",
    "..122333333221..",
    ".1.1.111111.1.1.",
]


def sprite_rows():
    """Pack the art into MARIA's 160A layout, one bytes-object per row."""
    rows = []
    for line in SHIP:
        if len(line) != SPRITE_WIDTH * 4:
            raise SystemExit("art row %r is not %d pixels"
                             % (line, SPRITE_WIDTH * 4))
        row = bytearray()
        for b in range(SPRITE_WIDTH):
            v = 0
            for p in range(4):
                c = line[b * 4 + p]
                v |= (0 if c == "." else int(c)) << (6 - 2 * p)
            row.append(v)
        rows.append(bytes(row))
    return rows


def source(title):
    rows = sprite_rows()
    hexb = lambda bs: ",".join("$%02X" % b for b in bs)

    # DL entry byte 1 packs palette in bits 7-5 and the width as 32 minus the
    # real width in bits 4-0. Width 4 therefore encodes as 28.
    width_field = (32 - SPRITE_WIDTH) & 0x1F

    L = []
    a = L.append
    a(";" * 74)
    a("; %s -- generated by newgame.py" % title)
    a(";")
    a("; Assemble and run:")
    a(";     python ../a7800-toolkit/tools/newgame.py . --build")
    a(";     mame a7800 -cart game.a78")
    a(";")
    a("; The three things that make this a 7800 program rather than a 6502 one")
    a("; are all in RESET below: the DLL, the DL, and the sprite layout.")
    a(";" * 74)
    a("")
    a("; ---- MARIA registers (docs/hardware.md) ----")
    for nm, ad in (("BACKGRND", 0x20), ("P0C1", 0x21), ("P0C2", 0x22),
                   ("P0C3", 0x23), ("MSTAT", 0x28), ("DPPH", 0x2C),
                   ("DPPL", 0x30), ("CHARBASE", 0x34), ("OFFSET", 0x38),
                   ("CTRL", 0x3C)):
        a("%-10s = $%02X" % (nm, ad))
    a("INPTCTRL   = $01")
    a("INPT4      = $0C        ; P1 button, bit 7 clear = pressed")
    a("SWCHA      = $0280      ; joystick directions, bit CLEAR = pushed")
    a("SWCHB      = $0282      ; console switches")
    a("")
    a("; ---- RAM (the 7800 has 4K at $1800-$27FF) ----")
    a("DLL        = $1800        ; %d zones x 3 bytes" % ZONES)
    a("DLBASE     = $1900        ; one display list per zone, 16 bytes apart")
    a("SHIPX      = $0080        ; zero page: the sprite's screen column")
    a("SHIPZONE   = $0082        ; which zone the ship is drawn in")
    a("FRAME      = $0081")
    a("")
    a("    .org $C000")
    a("")
    a("; ======================================================================")
    a("; RESET")
    a("; ======================================================================")
    a("reset:")
    a("    SEI")
    a("    CLD                       ; decimal mode survives reset on some parts")
    a("    LDX #$FF")
    a("    TXS")
    a("")
    a("    ; Take the machine off the BIOS and give MARIA to the cartridge.")
    a("    ; This pair -- an enable value, then zero -- is the sequence the")
    a("    ; 1987 cartridges use; see docs/hardware.md for the bits.")
    a("    LDA #$17")
    a("    STA INPTCTRL")
    a("    LDA #$00")
    a("    STA OFFSET                ; MARIA's own offset latch, not a DLL field")
    a("    STA INPTCTRL")
    a("")
    a("    ; DMA OFF while the lists are built. Pointing MARIA at a half-written")
    a("    ; display list is the classic way to get a screen full of garbage.")
    a("    LDA #$60                  ; CTRL bits 6-5 = 11 -> DMA off")
    a("    STA CTRL")
    a("")
    a("    ; ---- palette 0 ----")
    a("    ; Colour 0 of every palette IS the background: there is no separate")
    a("    ; transparent colour, which is why the art above uses '.' for it.")
    a("    LDA #$00")
    a("    STA BACKGRND")
    a("    LDA #$0F")
    a("    STA P0C1                  ; white")
    a("    LDA #$34")
    a("    STA P0C2                  ; red")
    a("    LDA #$18")
    a("    STA P0C3                  ; yellow")
    a("")
    a("    ; ---- build the Display List List ----")
    a("    ; One 3-byte entry per zone:")
    a("    ;   byte 0: flags | offset, where offset is SCANLINES MINUS ONE")
    a("    ;   byte 1: high byte of this zone's display list")
    a("    ;   byte 2: low byte")
    a("    ; The DLL may live in ROM -- MARIA fetches it by DMA and does not")
    a("    ; care. It is built in RAM here only because that is what a game")
    a("    ; that scrolls or reorders zones will need.")
    a("    LDX #$00                  ; X = zone * 3")
    a("    LDY #$00                  ; Y = zone * 16 -> this zone's DL low byte")
    a("dll_loop:")
    a("    LDA #$%02X" % (ZONE_LINES - 1))
    a("    STA DLL,X                 ; offset = %d lines - 1" % ZONE_LINES)
    a("    LDA #>DLBASE")
    a("    STA DLL+1,X")
    a("    TYA")
    a("    STA DLL+2,X")
    a("    INX")
    a("    INX")
    a("    INX")
    a("    TYA")
    a("    CLC")
    a("    ADC #$10")
    a("    TAY")
    a("    CPX #$%02X" % (ZONES * 3))
    a("    BNE dll_loop")
    a("")
    a("    ; ---- empty every display list ----")
    a("    ; A DL ends at the first entry whose byte 1 is zero, so zeroing the")
    a("    ; lot is the same as making every zone empty.")
    a("    LDX #$00")
    a("    LDA #$00")
    a("clear_dl:")
    a("    STA DLBASE,X")
    a("    INX")
    a("    CPX #$%02X" % (ZONES * 16))
    a("    BNE clear_dl")
    a("")
    a("    ; ---- put the ship in one zone ----")
    a("    ; A 4-byte DL entry:")
    a("    ;   byte 0: graphics address LOW")
    a("    ;   byte 1: palette (bits 7-5) | 32 - width (bits 4-0)")
    a("    ;   byte 2: graphics address HIGH")
    a("    ;   byte 3: horizontal position, in bytes")
    a("    ; Byte 1 must be non-zero or the entry terminates the list instead")
    a("    ; of drawing -- which is also why a width of 32 is unencodable.")
    a("    LDA #$00")
    a("    STA ship_dl+0             ; gfx low")
    a("    LDA #$%02X" % width_field)
    a("    STA ship_dl+1             ; palette 0, width %d" % SPRITE_WIDTH)
    a("    LDA #$%02X" % GFX_PAGE)
    a("    STA ship_dl+2             ; gfx high")
    a("    LDA #$28")
    a("    STA SHIPX")
    a("    STA ship_dl+3             ; x position, in PIXELS not bytes:")
    a("                              ; 0-159 in 160A mode, whatever the width")
    a("    LDA #$%02X" % (ZONES // 2))
    a("    STA SHIPZONE")
    a("")
    a("    ; ---- arm a display list interrupt ----")
    a("    ; Setting bit 7 of a DLL entry's byte 0 makes MARIA raise an")
    a("    ; interrupt at the END of that zone. On the 7800 that arrives as")
    a("    ; NMI, not IRQ, so SEI does not protect you from it -- the handler")
    a("    ; has to exist and be correct from the moment DMA comes on.")
    a("    ; This one repaints the palette halfway down, which is how a game")
    a("    ; gets more than eight palettes on a screen.")
    a("    LDA #$%02X                  ; bit 7 | offset" % (0x80 | (ZONE_LINES - 1)))
    a("    STA DLL+$%02X               ; byte 0 of zone %d" % (3 * (ZONES // 2 - 1), ZONES // 2 - 1))
    a("")
    a("    ; ---- point MARIA at the DLL and switch DMA on ----")
    a("    LDA #>DLL")
    a("    STA DPPH                  ; write-only: you cannot read these back")
    a("    LDA #<DLL")
    a("    STA DPPL")
    a("    LDA #$40                  ; DMA on, 160A. What Asteroids writes.")
    a("    STA CTRL")
    a("")
    a("; ======================================================================")
    a("; main loop -- one pass per frame")
    a("; ======================================================================")
    a("main:")
    a("    ; Wait for vertical blank. MSTAT bit 7 is set during VBLANK, so this")
    a("    ; waits for it to fall and then rise: one full frame, and the only")
    a("    ; safe window in which to touch a list MARIA is walking.")
    a("wait_low:")
    a("    LDA MSTAT")
    a("    BMI wait_low")
    a("wait_high:")
    a("    LDA MSTAT")
    a("    BPL wait_high")
    a("")
    a("    ; VBLANK: undo what the interrupt did, or the split only happens")
    a("    ; once. Anything a DLI changes has to be put back before the next")
    a("    ; frame starts drawing.")
    a("    LDA #$00")
    a("    STA BACKGRND")
    a("")
    a("    INC FRAME")
    a("")
    a("    ; ---- read the joystick ----")
    a("    ; SWCHA holds both sticks: player 1 in the HIGH nibble, and every")
    a("    ; bit is active LOW -- a clear bit means pushed. Testing it the")
    a("    ; obvious way round is the classic first input bug.")
    a("    ;   bit 7 right   bit 6 left   bit 5 down   bit 4 up")
    a("    LDA FRAME")
    a("    AND #$01                  ; move every other frame, so it is not")
    a("    BNE check_fire            ; unplayably fast")
    a("    LDA SWCHA")
    a("    AND #$40                  ; left?")
    a("    BNE try_right")
    a("    LDA SHIPX")
    a("    BEQ try_right             ; already at the edge")
    a("    DEC SHIPX")
    a("try_right:")
    a("    LDA SWCHA")
    a("    AND #$80                  ; right?")
    a("    BNE move_done")
    a("    LDA SHIPX")
    a("    CMP #$%02X                  ; 160 pixels across, less the sprite width" % (160 - SPRITE_WIDTH*4))
    a("    BCS move_done")
    a("    INC SHIPX")
    a("move_done:")
    a("    LDA SHIPX")
    a("    STA ship_dl+3")
    a("")
    a("check_fire:")
    a("    ; INPT4 bit 7 is CLEAR while the button is held.")
    a("    LDA INPT4")
    a("    BMI no_fire")
    a("    LDA #$0F                  ; flash white while fired")
    a("    STA P0C3")
    a("    JMP main")
    a("no_fire:")
    a("    LDA #$18")
    a("    STA P0C3")
    a("    JMP main")
    a("")
    a("; ======================================================================")
    a("; The display list entry we patch each frame.")
    a("; ======================================================================")
    a("; It lives in RAM, at the start of the zone %d display list." % (ZONES // 2))
    a("ship_dl    = DLBASE + $%02X" % ((ZONES // 2) * 16))
    a("")
    a("; ======================================================================")
    a("; SPRITE DATA -- and this is the part that is not like other machines.")
    a("; ======================================================================")
    a("; MARIA reads a direct-mode object one scanline at a time from")
    a("; CONSECUTIVE PAGES, and the offset counts DOWN: the TOP scanline is")
    a("; fetched from the HIGHEST page and the bottom one from the address in")
    a("; the display list. So the rows below are stored bottom-up, %d bytes" % 256)
    a("; apart, and the DL points at the LAST row. Store it as a flat bitmap")
    a("; and you get one row of your art repeated, or somebody else's data.")
    a(";")
    a("; .res fills the rest of each page. It is padding, not art.")
    a("")
    a("code_end:")
    a("    .res $%04X-code_end,$00" % (GFX_PAGE << 8))
    for i in range(SPRITE_LINES):
        row = rows[SPRITE_LINES - 1 - i]          # bottom row first
        a("ship_row%d:" % (SPRITE_LINES - 1 - i))
        a("    .byte %s" % hexb(row))
        if i != SPRITE_LINES - 1:
            a("    .res $100-%d,$00" % SPRITE_WIDTH)
    a("")
    a("; ======================================================================")
    a("; Vectors")
    a("; ======================================================================")
    a("; The display list interrupt. MARIA raises it as NMI at the end of the")
    a("; zone whose DLL entry has bit 7 set. Keep it SHORT: it runs inside the")
    a("; visible frame, and every cycle here is one the game does not get.")
    a("; Save what you use -- the main loop is mid-instruction underneath.")
    a("nmi:")
    a("    PHA")
    a("    LDA #$92                  ; everything below the split draws on blue")
    a("    STA BACKGRND")
    a("    PLA")
    a("    RTI")
    a("irq:")
    a("    RTI")
    a("")
    a("vectors_pad:")
    a("    .res $FFFA-vectors_pad,$00")
    a("    .word nmi")
    a("    .word reset")
    a("    .word irq")
    a("")
    return "\n".join(L) + "\n"


def header(size, title):
    """A 16K linear .a78 header. cart.py reads these; this writes one."""
    h = bytearray(128)
    h[0] = 1
    h[1:10] = b"ATARI7800"
    t = title.encode("latin1")[:32]
    h[17:17 + len(t)] = t
    h[49:53] = struct.pack(">I", size)
    h[53:55] = struct.pack(">H", 0x0000)      # linear, no mapper
    h[55] = 1                                 # joystick
    h[56] = 1
    h[57] = 0                                 # NTSC
    h[100:128] = b"ACTUAL CART DATA STARTS HERE"
    return bytes(h)


def build(outdir, title):
    import asm
    src = os.path.join(outdir, "game.asm")
    data = asm.Assembler().assemble(open(src, encoding="utf-8").read().splitlines())
    if len(data) != ROM_SIZE:
        raise SystemExit("assembled %d bytes, expected %d -- the .res padding "
                         "no longer reaches $FFFF" % (len(data), ROM_SIZE))
    out = os.path.join(outdir, "game.a78")
    with open(out, "wb") as f:
        f.write(header(len(data), title))
        f.write(data)
    return out, len(data)


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("outdir")
    ap.add_argument("--title", default="New Game")
    ap.add_argument("--build", action="store_true",
                    help="assemble the generated source into a .a78 too")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing game.asm")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    src = os.path.join(args.outdir, "game.asm")
    if os.path.exists(src) and not args.force:
        raise SystemExit("%s exists -- refusing to overwrite your source. "
                         "Pass --force if that is what you want." % src)
    with open(src, "w", encoding="utf-8") as f:
        f.write(source(args.title))
    print("wrote %s" % src)

    if args.build:
        out, n = build(args.outdir, args.title)
        print("wrote %s (%d bytes + 128-byte header)" % (out, n))
        print("")
        print("    mame a7800 -cart %s" % out)
    else:
        print("")
        print("assemble it with:")
        print("    python %s %s --build" % (os.path.relpath(__file__), args.outdir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
